<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agente Retencion' => '',
    'Ambito Catastro' => '',
    'Ano Inicio' => '',
    'Apto Dom' => '',
    'Are you sure you want to Incorporate this item?' => '',
    'Are you sure you want to Update this item?' => '',
    'Av Calle Esq Dom' => '',
    'Business Name' => '',
    'Capital' => '',
    'Casa Edf Qta Dom' => '',
    'Catastro' => '',
    'Create Inmuebles' => '',
    'Cuenta' => '',
    'Direccion' => '',
    'Domicilio Fiscal' => '',
    'Econ Informal' => '',
    'Email' => '',
    'Ente' => '',
    'Estado Catastro' => '',
    'Extension Horario' => '',
    'Fax' => '',
    'Fe Inic Agente Reten' => '',
    'Fecha' => '',
    'Fecha Inclusion' => '',
    'Fecha Inicio' => '',
    'Fecha Nac' => '',
    'First Names' => '',
    'Folio' => '',
    'Foraneo' => '',
    'Grupo Contribuyente' => '',
    'Horario' => '',
    'Id Contribuyente' => '',
    'Id Cp' => '',
    'Id Habitante' => '',
    'Id Impuesto' => '',
    'Id Rif' => '',
    'Id Sim' => '',
    'Id Taxpayer' => '',
    'Identifications' => '',
    'Inactivo' => '',
    'Inmuebles' => '',
    'Last Names' => '',
    'Licencia' => '',
    'Liquidado' => '',
    'Lote 1' => '',
    'Lote 2' => '',
    'Lote 3' => '',
    'Manzana Catastro' => '',
    'Manzana Limite' => '',
    'Medidor' => '',
    'Municipio Catastro' => '',
    'Naturaleza' => '',
    'Nit' => '',
    'Nivel' => '',
    'Nivel Catastro' => '',
    'No Declara' => '',
    'No Sujeto' => '',
    'Num Empleados' => '',
    'Num Reg' => '',
    'Observacion' => '',
    'Parcela Catastro' => '',
    'Parroquia Catastro' => '',
    'Phone Room' => '',
    'Piso Nivel No Dom' => '',
    'Propiedad Horizontal' => '',
    'Reg Mercantil' => '',
    'Representante' => '',
    'Reset' => '',
    'Ruc' => '',
    'Search' => '',
    'Sector Catastro' => '',
    'Sexo' => '',
    'Subparcela Catastro' => '',
    'Tipo' => '',
    'Tipo Contribuyente' => '',
    'Tipo Ejido' => '',
    'Tipo Naturaleza' => '',
    'Tlf Celular' => '',
    'Tlf Hab' => '',
    'Tlf Hab Otro' => '',
    'Tlf Ofic' => '',
    'Tlf Ofic Otro' => '',
    'Tomo' => '',
    'Unidad Catastro' => '',
];
