<?php
	return  [
    	'create' => [
    		'icon' => 'fa fa-file-text',
    		'class' => 'fa-2x',
    		'color' => $color,
    		'tipoIcon' => $tipoIcon[0],
    		'caption' => Yii::t('backend', 'Create'),
    		'title' => Yii::t('backend', 'Create'),
    		'url' => '#',
    	],
    	'save' => [
    		'icon' => 'fa fa-floppy-o',
    		'class' => 'fa-2x',
    		'color' => $color,
    		'tipoIcon' => $tipoIcon[0],
    		'caption' => Yii::t('backend', 'Update'),
    		'title' => Yii::t('backend', 'Update'),
    		'url' => '#',
    	],
        'update' => [
            'icon' => 'fa fa-pencil-square-o',
            'class' => 'fa-2x',
            'color' => $color,
            'tipoIcon' => $tipoIcon[0],
            'caption' => Yii::t('backend', 'Update'),
            'title' => Yii::t('backend', 'Update'),
            'url' => '#',
        ],
    	'list' => [
    		'icon' => 'fa fa-list',
    		'class' => 'fa-2x',
    		'color' => $color,
    		'tipoIcon' => $tipoIcon[0],
    		'caption' => Yii::t('backend', 'List'),
    		'title' => Yii::t('backend', 'List'),
    		'url' => '#',
    	],
    	'delete' => [
    		'icon' => 'fa fa-trash',
    		'class' => 'fa-2x',
    		'color' => $color,
    		'tipoIcon' => $tipoIcon[0],
    		'caption' => Yii::t('backend', 'Delete'),
    		'title' => Yii::t('backend', 'Delete'),
    		'url' => '#',
    	],
    	'print' => [
    		'icon' => 'fa fa-print',
    		'class' => 'fa-2x',
    		'color' => $color,
    		'tipoIcon' => $tipoIcon[0],
    		'caption' => Yii::t('backend', 'Print'),
    		'title' => Yii::t('backend', 'Print'),
    		'url' => '#',
    	],
        'search' => [
            'icon' => 'fa fa-binoculars',
            'class' => 'fa-2x',
            'color' => $color,
            'tipoIcon' => $tipoIcon[0],
            'caption' => Yii::t('backend', 'Search'),
            'title' => Yii::t('backend', 'Search'),
            'url' => '#',
        ],
        'quit' => [
            'icon' => 'fa fa-home',
            'class' => 'fa-2x',
            'color' => $color,
            'tipoIcon' => $tipoIcon[0],
            'caption' => Yii::t('backend', 'Quit'),
            'title' => Yii::t('backend', 'Quit'),
            'url' => '#',
        ],
        'back' => [
            'icon' => 'fa fa-arrow-left',
            'class' => 'fa-2x',
            'color' => $color,
            'tipoIcon' => $tipoIcon[0],
            'caption' => Yii::t('backend', 'Back'),
            'title' => Yii::t('backend', 'Back'),
            'url' => '#',
        ],
        'undo' => [
            'icon' => 'fa fa-undo',
            'class' => 'fa-2x',
            'color' => $color,
            'tipoIcon' => $tipoIcon[0],
            'caption' => Yii::t('backend', 'Undo'),
            'title' => Yii::t('backend', 'Undo'),
            'url' => '#',
        ],
        'help' => [
            'icon' => 'fa fa-question-circle',
            'class' => 'fa-2x',
            'color' => $color,
            'tipoIcon' => $tipoIcon[0],
            'caption' => Yii::t('backend', 'Help'),
            'title' => Yii::t('backend', 'Help'),
            'url' => '#',
            'target' => '_blank',

        ],
        //fa fa-question-circle
    ];

?>